### ISSUE TITLE
build system and warnings

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1374]
With mirage 4, I fail to find a `warn-error` option (this has been removed in 76db9815542270b154eef8db8f33e80da9388276 by @samoht). Now the question is, since `(profile release)` is unconditionally emitted into `dune-workspace`; and there's ` (flags (:standard -warn-error -A))` unconditionally put into `dune.config`, how can I see warnings and errors?

I recently manually removed both profile and the flags in qubes firewall, and that exposed some unused opens and unused functions, which I never saw a warning about before (see https://github.com/mirage/qubes-mirage-firewall/pull/161). Any suggestion how to observe warnings would be highly welcome.

**Comment by samoht** [comment]
I hadn't realised that we were building with `-warn-error -A` unconditionally. I suggest that we just remove this line. Would that help?

I'm also happy to re-introduce a flag to not build in release mode during development.

**Comment by hannesm** [comment]
> I hadn't realised that we were building with `-warn-error -A` unconditionally

this is there since 87a661e73

> I suggest that we just remove this line. Would that help?

I guess it would. But I've no clue about the side effects and why it was set up as it is now.

> I'm also happy to re-introduce a flag to not build in release mode during development.

I again have not much knowledge of the tradeoffs, I only remember that "not using release mode for JS_of_OCaml leads to huge binaries". So the default (mirage build / dune build) should likely be `release` (in contrast to what `dune` uses as default), but I've no idea whether dune with a default profile set to release via dune-workspace respects the `--profile=dev`?

**Comment by samoht** [comment]
> I've no idea whether dune with a default profile set to release via dune-workspace respects the --profile=dev

yes it does - I suspect that Lucas disabled the warnings to not fail for warnings in vendored dependencies. This has been fixed a while ago (as warnings in `duniverse/` are not an error anymore) and thus could be reverted safely (just need to double check with @TheLortex that it was its initial intention).

And it's indeed better to use the `release` mode for generated unikernels, for instance, to make sure cross-module inlining is enabled.

**Comment by hannesm** [comment]
> > I suggest that we just remove this line. Would that help?
>
> I guess it would. But I've no clue about the side effects and why it was set up as it is now.

Unfortunately it doesn't help too much (done in #1379), since it's only in dune.config and affecting the compilation of config.exe

The real issue is the `profile release` as default. Since I barely know anything what dune does with it under the hood, I'm still puzzled what we should do.

In mirage3 days, we had the `warn-error` flag to treat warnings as errors. Maybe we can (a) put in the default warnings into the dune release profile and (b) re-introduce `warn-error` to error for warnings?

Or maybe, instead of trying to tweak the default profile for mirage, just use the development profile and on invocation of `mirage build` warn that "in order to build artifacts with high performance, use `--profile=release`"? Now, there's still the issue that `mirage build` would/should accept all the arguments `dune` accepts -- which is painful.

So, my current proposal is:
- mirage build to just emit "please use dune build --profile=release for to-be-released artifacts / dune build for development"
- drop the profile release from the dune-workspace
- in the generated opam file emit the dune build --profile=release, as in the generated Makefile

WDYT?

**Comment by hannesm** [comment]
The above comment definitively needs some further refinements, since `mirage build` is not equivalent to `dune build` -- it is `dune build --root .`, but additionally there's some `dune` file generated in the build_dir with `include dune.build`. I'm still not sure what the expected behaviour of passing `-f <path-to-config-file>` to mirage is, maybe someone could describe this more precisely what the intention is?

Does a `mirage configure -f path/to/config.ml` generate stuff in the current working directory? or next to path/to/config.ml? Are relative and/or absolute paths supported?

Does a subsequent `mirage build` work? Or does this need to have `-f path/to/config.ml` added as well? If yes, why? What's the purpose of the `-f` flag, will the build directory be in the current working directory or somewhere close to config.ml?

I tried in the past several times to use `-f` and was always confused, leading to me just using `cd` to the right directory and eventually putting some symbolic links.

**Comment by TheLortex** [comment]
Hi, I'd like to spend some time on improving the mirage / dune integration, especially in terms of _composability_. I'll try to come up with a document explaining how to improve the current scheme.

> I'm still not sure what the expected behaviour of passing -f <path-to-config-file> to mirage is, maybe someone could describe this more precisely what the intention is?

When running `mirage configure`, `mirage` sets up a _`dune-workspace`_ file in the current working directory. This file describe the _global_ configuration for the workspace (in particular which compiler to use). The build will include libraries that are defined in the workspace.

For larger projects, one can have a workspace containing a `mirage/` folder with a unikernel, and a supporting library in `lib/`. In that case it's useful to call `mirage configure -f mirage/config.ml` to configure a unikernel in a subfolder, while setting up the _workspace_ to contain both the unikernel and the supporting library.

**Comment by hannesm** [comment]
Thanks for your reply @TheLortex. So a `mirage configure -f /path/to/config.ml` puts stuff into the current working directory. Does a `mirage build` / `dune build` then produce the binary (in `dist/unikernel.exe`)? Does the `mirage build` need a `-f` as well?

> I'd like to spend some time on improving the mirage / dune integration, especially in terms of composability.

Not sure I understand what you'd like to compose. But please go ahead.

**Comment by TheLortex** [comment]
>  Does a mirage build / dune build then produce the binary (in dist/unikernel.exe)?

Yes. There's a dune file in `dist/` which specifies that the binary is promoted to the source tree when built.

> Not sure I understand what you'd like to compose. 

I mean to have composability in the _dune_ sense:
> Dune is composable, meaning that multiple Dune projects can be arranged together, leading to a single build that Dune knows how to execute. This allows for monorepos of projects.
>
> Dune makes simultaneous development on multiple packages a trivial task. 

I'd like to be able to manage multiple unikernels configurations in the same workspace. Currently we can only configure a single unikernel as dune files are generated in the source tree. Instead, a mirage unikernel configuration could remain contained in a specific folder. There are also problems compiling the `config.ml` when a duniverse folder is present in the source tree.

**Comment by hannesm** [comment]
Thanks for your reply. I'm as well very interested in "manage multiple unikernels configurations in the same workspace".

But first of all, I'd like to be able to see warnings from the unikernel source without having to manually edit generated files. Would this be possible?

> > Does a mirage build / dune build then produce the binary (in dist/unikernel.exe)?
>
> Yes. There's a dune file in dist/ which specifies that the binary is promoted to the source tree when built.

I was especially curious about where specific commands are executed (working directory) and when commands are getting the config.ml file passed explicitly (`mirage configure -f ...` outputs some stuff into the working directory or into the unikernel directory (where `-f` points to)? -- and why and what is the purpose to be able to specify `-f`?). Does from any working directory, a subsequent `mirage build` also need a `-f`? Would it simplify a lot if `mirage` would not need to deal with `-f` (in terms of code complexity, but also intuition from the user, where to expect which files).

**Comment by hannesm** [comment]
now "mirage build" is no more, and a "make build" is `dune build --profile release --root . $(BUILD_DIR)dist` -- so that's easy to tweak (disable/enable warnings, etc.) :) (the last statement is true once #1470 is merged).
